### ISSUE TITLE
`done()` is unsound and should be marked `unsafe`

### ISSUE THREAD

**Issue by jonas-schievink** [Xudong-Huang/generator-rs#13]
`done` is equivalent to `mem::uninitialized` and thus can be used to trivially construct uninitialized instances of types.

The function is documented "don't use it directly, use done!() macro instead", but it's neither hidden nor marked as `unsafe`, both should probably be done.

This results in a segmentation fault on my machine:

```rust
use generator::{co_get_yield, co_set_para, Gn, done};

fn main() {
    done::<(String, Vec<u128>, Box<[u128]>)>();
}
```

**Comment by Xudong-Huang** [comment]
`done` can't not be called in non-coroutine context.  Will add more checks here.

**Comment by Xudong-Huang** [comment]
`done` should be a safe API. in generator context, we didn't touch the uninit memory. and will panic in non-generator context.
