### ISSUE TITLE
Free function `yield_` is unsound

### ISSUE THREAD

**Issue by jonas-schievink** [Xudong-Huang/generator-rs#14]
It can be used to transmute types. Example causing a segmentation fault (at least on my machine):

```rust
use generator::*;

fn main() {
    let g = Gn::new_scoped(|_| {
        yield_::<String, _>(());
    });

    for () in g {}
}
```

**Comment by Xudong-Huang** [comment]
`yied_` should be deprecated. we should always use scoped version's yield method.

**Comment by Xudong-Huang** [comment]
now if call deprecated `yield_` in a scoped generator, this will trigger assertion panic.
