### ISSUE TITLE
What causes this, here we just panic to exit the func??

### ISSUE THREAD

**Issue by Bajix** [Xudong-Huang/generator-rs#32]
I am intermittently getting the error `thread 'tests::stealer_takes_blocking' panicked at 'Box<dyn Any>', /Users/aozen/.cargo/registry/src/github.com-1ecc6299db9ec823/generator-0.7.0/src/yield_.rs:60:9`  while testing some code changes under Loom to evaluate Consume memory orderings. This usually passes all tests, but when it doesn't and I get this error, when I check the source code all this says is `// here we just panic to exit the func`, so that does mean? I can't tell from this if an error even exists, and here I have ASAN/LSAN/TSAN/Miri/Loom testing all showing this works correctly in most runs.

This is the code in question: https://github.com/Bajix/swap-queue-rs/tree/feature/consume-ordering

**Comment by Xudong-Huang** [comment]
the `_ref` field is designed to track if the generator is running, yield will -1, send will +1. when it's value is 1 it means that the generator is running, 0 means it's not running. Usually when yield back to generator, we check the `_ref` value must be equal to 1. or we just panic when cancel was triggered.
