### ISSUE TITLE
大佬，问下汇编推荐什么书？

### ISSUE THREAD

**Issue by loongs-zhang** [Xudong-Huang/generator-rs#35]
大佬，问下汇编推荐什么书？

**Comment by Xudong-Huang** [comment]
我没有看过系统的书籍，基本上是用到什么，就去搜下

**Comment by loongs-zhang** [comment]
好的，请问可以加个微信吗？后续我可能需要请教您。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Xudong Huang ***@***.***&gt;
发送时间: 2022年3月8日 09:15
收件人: Xudong-Huang/generator-rs ***@***.***&gt;
抄送: dragon-zhang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Xudong-Huang/generator-rs] 大佬，问下汇编推荐什么书？ (Issue #35)





 
我没有看过系统的书籍，基本上是用到什么，就去搜下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
