### ISSUE TITLE
Why yanked 0.7.6？ 

### ISSUE THREAD

**Issue by Borber** [Xudong-Huang/generator-rs#56]
![image](https://github.com/Xudong-Huang/generator-rs/assets/30563826/699d4b2d-f5b3-4d2d-a983-f1638d8b42d3)

**Comment by Xudong-Huang** [comment]
ref https://github.com/Xudong-Huang/generator-rs/issues/54
it's a breaking change

**Comment by Xudong-Huang** [comment]
use 0.8.0 should be fine

**Comment by Borber** [comment]
> use 0.8.0 should be fine

ok, thanks for the answer
