### ISSUE TITLE
Cargo test --release failed

### ISSUE THREAD

**Issue by joyious** [Xudong-Huang/generator-rs#8]
error: process didn't exit successfully: `/Users/joyious/Workspace/sdag/generator-rs/target/release/deps/generator-fbaeb80c50e742bc` (signal: 11, SIGSEGV: invalid memory reference)

**Comment by Xudong-Huang** [comment]
Oh, I think this failed on MacOs only

I added release version test, and found that it only failed on MacoOS|nightly|release version!

**Comment by Xudong-Huang** [comment]
fix in 0.6.12
